"""Tests for the content policy (no AI signature) and the PreToolUse hook that applies it.

Run: python3 -m unittest discover -s tests
"""
import io
import json
import pathlib
import re
import subprocess
import sys
import tempfile
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "hooks"))
import content_policy  # noqa: E402
import pre_tool_use  # noqa: E402

POLICY = ROOT / "policies" / "content-policy.json"

# Texts that must be refused, with the pattern that should catch each.
SIGNED = {
    "ai-co-author-trailer": [
        "Co-Authored-By: Claude Sonnet 5.5 <noreply@anthropic.com>",
        "Co-authored-by: Copilot <copilot@github.com>",
        "Co-Authored-By: ChatGPT <bot@example.com>",
        "co-authored-by: an AI assistant",
        "Co-Authored-By: AI assistant",
    ],
    "ai-vendor-address": ["Co-Authored-By: Assistant <helper@anthropic.com>", "Reviewer <x@mail.openai.com>"],
    "generated-with-footer": [
        "Generated with Claude Code",
        "\U0001F916 Generated with [Claude Code](https://claude.com/claude-code)",
        "generated by an AI assistant",
        "Generated using AI",
        "Generated by ChatGPT",
    ],
    "sign-off-by-ai": [
        "Signed by AI",
        "Signed-off-by: Claude <x@y.z>",
        "Edited by an AI assistant",
        "Published by AI",
        "Written by ChatGPT",
        "Reviewed by Gemini",
        "Drafted by GPT-4",
        "Authored by Claude",
        "Merged by Claude",
        "Fixed by an AI",
        "Assisted-by: Claude",
    ],
    "claude-code-link": ["See https://claude.com/claude-code", "claude.ai/code/session"],
    "robot-emoji": ["Done \U0001F916"],
}

# Texts that must pass: human co-authors, people named Ai, ordinary prose about AI, other generators.
CLEAN = [
    "Co-authored-by: Jane Doe <jane@example.com>",
    "Co-authored-by: Ai Nguyen <ai.nguyen@example.com>",
    "Written by Ai Nguyen",
    "AI-Assisted Data Engineering Consulting Platform",
    "Uses Claude Code as the agent runtime",
    "Generated by dbt docs generate",
    "Generated with the Fabric REST API",
    "approved by AI governance board",
    "Reviewed by the team and signed off by the product owner",
    "Fixed by the data platform team",
    "Assisted by Ai Nguyen",
    "Fix null handling in silver.orders",
]


def bash(command, cwd=None):
    return {"tool_name": "Bash", "tool_input": {"command": command}, "cwd": str(cwd or ROOT)}


def verdict(event, path=POLICY):
    out = content_policy.decide(event, path)
    return out["hookSpecificOutput"]["permissionDecision"] if out else None


class PolicyFileTest(unittest.TestCase):
    def test_it_loads_and_every_pattern_has_an_example(self):
        policy = content_policy.load_policy(POLICY)
        names = [name for name, _ in policy.patterns]
        self.assertEqual(len(names), len(set(names)))
        self.assertEqual(set(names), set(SIGNED), "every pattern needs a signed example, and the reverse")

    def test_every_signed_example_is_found_by_its_own_pattern(self):
        policy = content_policy.load_policy(POLICY)
        for name, examples in SIGNED.items():
            for text in examples:
                self.assertIn(name, [n for n, _ in content_policy.find_signatures(text, policy)], text)

    def test_clean_text_is_never_flagged(self):
        policy = content_policy.load_policy(POLICY)
        for text in CLEAN:
            self.assertEqual(content_policy.find_signatures(text, policy), [], text)


class ShellCommandTest(unittest.TestCase):
    def test_publishing_commands_with_a_signature_are_denied(self):
        for command in (
            'git commit -m "fix: nulls" -m "Co-Authored-By: Claude <noreply@anthropic.com>"',
            "git commit -F - <<'EOF'\nfix: nulls\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nEOF",
            'cd repo && git commit -m "x" -m "\U0001F916 Generated with Claude Code"',
            "git -C /tmp/r commit -m 'x\n\nGenerated with Claude Code'",
            'FOO=1 git commit -m "Signed by AI"',
            'sudo git tag -a v1 -m "Published by AI"',
            'gh pr create --title t --body "Done.\n\n\U0001F916 Generated with [Claude Code](https://claude.com/claude-code)"',
            'gh issue comment 3 --body "Signed by AI"',
            'gh api repos/o/r/issues -f body="Edited by an AI assistant"',
            'git merge feature -m "Merged by Claude"',
        ):
            self.assertEqual(verdict(bash(command)), "deny", command)

    def test_the_reason_names_the_rule_the_text_and_the_pattern(self):
        out = content_policy.decide(bash('git commit -m "Signed by AI"'), POLICY)["hookSpecificOutput"]
        self.assertEqual(out["hookEventName"], "PreToolUse")
        reason = out["permissionDecisionReason"]
        for part in ("CP-01", "Signed by AI", "sign-off-by-ai", "commit, pull request or issue command"):
            self.assertIn(part, reason)
        self.assertNotIn("{matched}", reason)
        self.assertNotIn("{where}", reason)

    def test_commands_that_only_read_or_are_not_publishing_pass(self):
        for command in (
            'git commit -m "fix: handle nulls"',
            "git commit --amend --no-edit",
            'git log --grep="Co-Authored-By: Claude"',
            'grep -rn "Generated with Claude Code" .',
            'echo "Signed by AI" > notes.txt',
            "git diff --stat",
            "python3 -m unittest discover -s tests",
            'gh pr list --search "Generated with Claude Code"',
            "ls",
        ):
            self.assertIsNone(verdict(bash(command)), command)

    def test_a_message_file_is_read(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp = pathlib.Path(tmp)
            (tmp / "signed.txt").write_text("fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n")
            (tmp / "clean.txt").write_text("fix: handle nulls\n")
            self.assertEqual(verdict(bash("git commit -F signed.txt", tmp)), "deny")
            self.assertEqual(verdict(bash("git commit --file=signed.txt", tmp)), "deny")
            self.assertEqual(verdict(bash(f"gh pr create --title t --body-file {tmp}/signed.txt", tmp)), "deny")
            self.assertIsNone(verdict(bash("git commit -F clean.txt", tmp)))
            self.assertIsNone(verdict(bash("git commit -F missing.txt", tmp)))
            self.assertIsNone(verdict(bash("git commit -F -", tmp)))


class FileWriteTest(unittest.TestCase):
    def write(self, path, content):
        return {"tool_name": "Write", "tool_input": {"file_path": path, "content": content}}

    def edit(self, path, old, new):
        return {"tool_name": "Edit", "tool_input": {"file_path": path, "old_string": old, "new_string": new}}

    def test_ticket_decision_and_runbook_notes_are_protected(self):
        for path in ("/work/repo/.ai/tickets/T-1.md", ".ai/adr/ADR-1.md", "/w/r/.ai/runbooks/rerun.md",
                     "/w/r/.git/COMMIT_EDITMSG", "C:\\w\\r\\.ai\\tickets\\T-2.md"):
            self.assertEqual(verdict(self.write(path, "# Note\n\nSigned by AI\n")), "deny", path)
            self.assertIsNone(verdict(self.write(path, "# Note\n\nPlain text.\n")), path)

    def test_other_files_are_not_inspected(self):
        for path in ("/w/r/README.md", "/w/r/tests/test_x.py", "/w/r/docs/notes.md", "/w/r/src/ai/tickets_x.py"):
            self.assertIsNone(verdict(self.write(path, "Signed by AI")), path)

    def test_a_signature_can_be_removed(self):
        path = "/w/r/.ai/tickets/T-1.md"
        self.assertEqual(verdict(self.edit(path, "x", "Edited by Claude")), "deny")
        self.assertIsNone(verdict(self.edit(path, "Edited by Claude", "")))

    def test_multi_edit_is_checked_per_edit(self):
        path = "/w/r/.ai/adr/ADR-1.md"
        clean = {"tool_name": "MultiEdit", "tool_input": {"file_path": path, "edits": [
            {"old_string": "a", "new_string": "b"}, {"old_string": "Signed by AI", "new_string": ""}]}}
        signed = {"tool_name": "MultiEdit", "tool_input": {"file_path": path, "edits": [
            {"old_string": "a", "new_string": "b"}, {"old_string": "c", "new_string": "Signed by AI"}]}}
        self.assertIsNone(verdict(clean))
        self.assertEqual(verdict(signed), "deny")


class OtherToolsTest(unittest.TestCase):
    def test_create_and_update_mcp_tools_are_checked_but_reads_are_not(self):
        body = {"title": "Bug", "body": "Fixed.\n\n\U0001F916 Generated with Claude Code"}
        for tool in ("mcp__github__create_issue", "mcp__ado__update_work_item", "mcp__github__add_issue_comment"):
            self.assertEqual(verdict({"tool_name": tool, "tool_input": body}), "deny", tool)
            self.assertIsNone(verdict({"tool_name": tool, "tool_input": {"title": "Bug", "body": "Fixed."}}), tool)
        self.assertIsNone(verdict({"tool_name": "mcp__github__get_issue", "tool_input": body}))

    def test_other_tools_are_ignored(self):
        for tool in ("Read", "Grep", "Glob", "WebFetch", "Task"):
            self.assertIsNone(verdict({"tool_name": tool, "tool_input": {"command": "Signed by AI"}}), tool)


class BrokenPolicyTest(unittest.TestCase):
    """A policy that cannot be read must not silently switch itself off."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.dir = pathlib.Path(self._tmp.name)

    def bad_files(self):
        yield self.dir / "missing.json"
        broken = self.dir / "broken.json"
        broken.write_text("{not json", encoding="utf-8")
        yield broken
        empty = self.dir / "empty.json"
        empty.write_text(json.dumps({"rules": {"no_ai_signature": {"message": "m", "patterns": []}},
                                     "scope": {"bash_publishing_commands": [], "files": [], "mcp_tools": "x"}}))
        yield empty
        bad_regex = self.dir / "regex.json"
        data = json.loads(POLICY.read_text())
        data["rules"]["no_ai_signature"]["patterns"][0]["regex"] = "(unclosed"
        bad_regex.write_text(json.dumps(data))
        yield bad_regex

    def test_calls_likely_to_be_in_scope_ask_a_person(self):
        for path in self.bad_files():
            self.assertRaises(content_policy.PolicyError, content_policy.load_policy, path)
            for event in (bash('git commit -m "x"'), bash("gh pr create --title t"),
                          {"tool_name": "Write", "tool_input": {"file_path": "/r/.ai/tickets/T.md", "content": "x"}},
                          {"tool_name": "mcp__github__create_issue", "tool_input": {"body": "x"}}):
                out = content_policy.decide(event, path)
                self.assertEqual(out["hookSpecificOutput"]["permissionDecision"], "ask", (path.name, event))
                self.assertIn("could not be read", out["hookSpecificOutput"]["permissionDecisionReason"])

    def test_unrelated_calls_are_left_alone(self):
        for path in self.bad_files():
            self.assertIsNone(content_policy.decide(bash("ls -la"), path))
            self.assertIsNone(content_policy.decide({"tool_name": "Write", "tool_input": {
                "file_path": "/r/src/app.py", "content": "x"}}, path))


class HookTest(unittest.TestCase):
    def run_main(self, text):
        out, err = io.StringIO(), io.StringIO()
        code = pre_tool_use.main(io.StringIO(text), out, err)
        return code, out.getvalue(), err.getvalue()

    def test_a_signed_commit_is_denied_as_json(self):
        code, out, _ = self.run_main(json.dumps(bash('git commit -m "Signed by AI"')))
        self.assertEqual(code, 0)
        self.assertEqual(json.loads(out)["hookSpecificOutput"]["permissionDecision"], "deny")

    def test_a_clean_call_prints_nothing(self):
        code, out, _ = self.run_main(json.dumps(bash('git commit -m "fix: nulls"')))
        self.assertEqual((code, out), (0, ""))

    def test_input_that_is_not_json_does_not_crash(self):
        code, out, err = self.run_main("not json")
        self.assertEqual((code, out), (0, ""))
        self.assertIn("not JSON", err)

    def test_a_crashing_check_asks_a_person(self):
        original = content_policy.decide
        content_policy.decide = lambda event: 1 / 0
        try:
            code, out, _ = self.run_main(json.dumps(bash("ls")))
        finally:
            content_policy.decide = original
        self.assertEqual(code, 0)
        self.assertEqual(json.loads(out)["hookSpecificOutput"]["permissionDecision"], "ask")

    def test_it_runs_as_a_script_the_way_claude_code_runs_it(self):
        signed = subprocess.run([sys.executable, str(ROOT / "hooks" / "pre_tool_use.py")],
                                input=json.dumps(bash('gh pr create --body "Signed by AI"')),
                                capture_output=True, text=True)
        self.assertEqual(signed.returncode, 0, signed.stderr)
        self.assertEqual(json.loads(signed.stdout)["hookSpecificOutput"]["permissionDecision"], "deny")
        clean = subprocess.run([sys.executable, str(ROOT / "hooks" / "pre_tool_use.py")],
                               input=json.dumps(bash("git status")), capture_output=True, text=True)
        self.assertEqual((clean.returncode, clean.stdout), (0, ""))


class RegistrationAndSettingsTest(unittest.TestCase):
    def test_the_plugin_registers_the_policy_hook_for_the_tools_it_inspects(self):
        config = json.loads((ROOT / "hooks" / "hooks.json").read_text())
        entries = config["hooks"]["PreToolUse"]
        self.assertEqual(len(entries), 1)
        matcher = re.compile(entries[0]["matcher"])
        for tool in ("Bash", "Read", "Grep", "Glob", "Write", "Edit", "MultiEdit", "NotebookEdit",
                     "mcp__github__create_issue"):
            self.assertTrue(matcher.fullmatch(tool) or matcher.match(tool), tool)
        for tool in ("WebFetch", "Task", "TodoWrite"):
            self.assertIsNone(matcher.fullmatch(tool), tool)
        handler = entries[0]["hooks"][0]
        self.assertEqual(handler["type"], "command")
        self.assertGreater(handler["timeout"], 0)
        script = handler["command"].replace("${CLAUDE_PLUGIN_ROOT}", str(ROOT)).split('"')[1]
        self.assertTrue(pathlib.Path(script).is_file(), script)

    def test_claude_codes_own_attribution_is_switched_off_here_and_in_the_template(self):
        for path in (ROOT / ".claude" / "settings.json",
                     ROOT / "templates" / "client-project" / ".claude" / "settings.json"):
            settings = json.loads(path.read_text())
            self.assertEqual(settings["attribution"], {"commit": "", "pr": "", "sessionUrl": False}, str(path))

    def test_agents_are_told_not_to_route_around_a_policy(self):
        self.assertIn("Policies are not obstacles to route around", (ROOT / "AGENTS.md").read_text())

    def test_the_rule_is_stated_for_agents_here_and_in_every_new_project(self):
        for path in (ROOT / "AGENTS.md", ROOT / "templates" / "AGENTS.md"):
            self.assertIn("No AI signature", path.read_text(), str(path))

    def test_nothing_the_framework_ships_tells_an_agent_to_sign_its_work(self):
        policy = content_policy.load_policy(POLICY)
        exempt = {ROOT / "AGENTS.md", ROOT / "templates" / "AGENTS.md"}
        hits = []
        for folder in ("skills", "commands", "agents", "standards", "templates", "inbox"):
            for path in (ROOT / folder).rglob("*"):
                if path.is_file() and path not in exempt and path.suffix in (".md", ".yaml", ".json", ".sh"):
                    for name, matched in content_policy.find_signatures(path.read_text(encoding="utf-8"), policy):
                        hits.append(f"{path.relative_to(ROOT)}: {name}: {matched}")
        self.assertEqual(hits, [])


if __name__ == "__main__":
    unittest.main()
